# Regression Task in Deep Learning

Example: Predicting House Prices

Another common type of machine learning problem is "regression", which consists of predicting a continuous value instead of a discrete label. For instance, predicting the temperature tomorrow, given meteorological data, or predicting the time that a software project will take to complete, given its specifications.

In [ ]:
# Import Modules
import keras
# Load the data: Boston Housing Price
from keras.datasets import boston_housing
# Modeling
from keras import models
from keras import layers
# Validation
from keras import backend as K
# NumPy
import numpy as np
# Plot
import matplotlib.pyplot as plt


In [ ]:
# Check Keras version
keras.__version__

'2.2.5'

## The Boston Housing Price Dataset

We will be attempting to predict the median price of homes in a given Boston suburb in the mid-1970s, given a few data points about the suburb at the time, such as the crime rate, the local property tax rate, etc.

The dataset we will be using has another interesting difference from our two previous examples: it has very few data points, only 506 in total, split between 404 training samples and 102 test samples, and each "feature" in the input data (e.g. the crime rate is a feature) has a different scale. For instance some values are proportions, which take a values between 0 and 1, others take values between 1 and 12, others between 0 and 100...

In [ ]:
# Load the data
#from keras.datasets import boston_housing

(train_data, train_targets), (test_data, test_targets) =  boston_housing.load_data()

<module 'keras.datasets.boston_housing' from '/usr/local/lib/python3.6/dist-packages/keras/datasets/boston_housing.py'>


In [ ]:
train_data.shape

(404, 13)

In [ ]:
test_data.shape

(102, 13)

At all, 404 training samples and 102 test samples. The data comprises 13 features. The 13 features in the input data are as follow:

- Per capita crime rate.
- Proportion of residential land zoned for lots over 25,000 square feet.
- Proportion of non-retail business acres per town.
- Charles River dummy variable (= 1 if tract bounds river; 0 otherwise).
- Nitric oxides concentration (parts per 10 million).
- Average number of rooms per dwelling.
- Proportion of owner-occupied units built prior to 1940.
- Weighted distances to five Boston employment centres.
- Index of accessibility to radial highways.
- Full-value property-tax rate per $10,000.
- Pupil-teacher ratio by town.
- 1000 * (Bk - 0.63) ** 2 where Bk is the proportion of Black people by town.
- % lower status of the population.

The targets are the median values of owner-occupied homes, in thousands of dollars:


In [ ]:
# Inspect target
train_targets[0:10]

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4])

The prices are typically between \$10,000 and \$50,000. If that sounds cheap, remember this was the mid-1970s, and these prices are not inflation-adjusted.

## Prepare the data
Range of all variables should be equal-model then trains faster!

In [ ]:
#First we have to get the mean and sd of the training data
mean = train_data.mean(axis = 0)
sd = train_data.std(axis=0)

In [ ]:
#Transformation (Z-transformation)

train_data -= mean # -= subtract the mean from every value in a column

train_data /= sd

In [ ]:
# Validate results:
train_data.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#Transformation (Z-transformation)

test_data -= mean # -= subtract the mean from every value in a column

test_data /= sd

## Build Network

activation: 'relu' only

input_shape = (train_data.shape[1],)

In [ ]:
network = models.Sequential()
network.add(layers.Dense(64, activation='relu', input_shape = (13,)))
network.add(layers.Dense(1))

In [ ]:
## Summary of network
network.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 64)                896       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 65        
Total params: 961
Trainable params: 961
Non-trainable params: 0
_________________________________________________________________


### Initialization - Part 2
- Loss-function: `mse` #Mean Squared Error
- optimizer: `rmsprop`
- Metrics: `mae` #Mean Average Error

In [ ]:
network.compile(optimizer='rmsprop', loss='mse',metrics=['mape', 'mae'])

In [ ]:
network.fit(train_data, train_targets,epochs=40)

Epoch 1/40
404/404 [==============================] - 0s 411us/step - loss: 13.7509 - mean_absolute_percentage_error: 13.2228 - mean_absolute_error: 2.6028
Epoch 2/40
404/404 [==============================] - 0s 43us/step - loss: 13.4502 - mean_absolute_percentage_error: 12.7227 - mean_absolute_error: 2.5469
Epoch 3/40
404/404 [==============================] - 0s 45us/step - loss: 13.2123 - mean_absolute_percentage_error: 12.6645 - mean_absolute_error: 2.5348
Epoch 4/40
404/404 [==============================] - 0s 45us/step - loss: 12.9581 - mean_absolute_percentage_error: 12.4402 - mean_absolute_error: 2.4949
Epoch 5/40
404/404 [==============================] - 0s 52us/step - loss: 12.7730 - mean_absolute_percentage_error: 12.4243 - mean_absolute_error: 2.4860
Epoch 6/40
404/404 [==============================] - 0s 46us/step - loss: 12.6015 - mean_absolute_percentage_error: 12.4165 - mean_absolute_error: 2.4693
Epoch 7/40
404/404 [==============================] - 0s 52us/step - 

In [ ]:
test_loss, test_mape, test_mae = network.evaluate(x=test_data, y=test_targets)

102/102 [==============================] - 0s 706us/step


In [ ]:
print("MAPE:", test_mape)

MAPE: 14.785228691849055


In [ ]:
plo